development:
  mysql:
    host: gsdb.cjzyegeqvbre.us-west-2.rds.amazonaws.com
    user: gsmaster
    password: cpdhEV3bqWa4TNVEAJSTqxSf
    db: gsmaster
    port: 3306
    engine: 'mysql://gsmaster:cpdhEV3bqWa4TNVEAJSTqxSf@gsdb.cjzyegeqvbre.us-west-2.rds.amazonaws.com:3306/gsmaster'
  api_keys:
    internal_api:
    giphy_api:
  other:
    debug: True

production:
  mysql:
    host:
    user:
    password:
    db:
  api_keys:
    internal_api:
    giphy_api:
  other:
    debug: false